#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := nesemu-go
EXTRA_COMPONENT_DIRS := ~/Desktop/github/RetroESP32/Public/Software/Emulators/retro-go/components
#EXTRA_COMPONENT_DIRS := $(dirname "$PWD")/components

include $(IDF_PATH)/make/project.mk
