#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := nesemu-go

CWD := $(shell cd ../ && (bash -c "dirs +0"))
EXTRA_COMPONENT_DIRS := ~/Desktop/github/R32/Software/Emulators/retro-go/components

$(info    CWD is $(CWD))
$(info    EXTRA_COMPONENT_DIRS is $(EXTRA_COMPONENT_DIRS))

include $(IDF_PATH)/make/project.mk
