#!/bin/zsh

# port
bauds() {
  
  BAUDS=("115200" "230400" "460800" "921600" "2000000")
  OPTION="${monkey}  ${red}Please Select ${cyan}Baud Rate${nc}"
  echo "\n--------------------------------------------------------------------------"
  echo "\n${OPTION}"
  echo "\n--------------------------------------------------------------------------"  
  select BAUD in "${BAUDS[@]}"
  do
    case $BAUD in
      * ) 
        if [[ $BAUD[0,1] ]]
        then
          clear
          echo "\n--------------------------------------------------------------------------"
          echo "\n${squid}  ${green}Selected ${cyan}${BAUD#*.}${nc} Baud Rate"
          echo "\n--------------------------------------------------------------------------"
          sleep 0.5
          clear
          break
        else
          bauds
        fi
    esac
  done  
}

bauds