#!/bin/zsh

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erase Flash ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
    clear
    echo "\n--------------------------------------------------------------------------"
    echo "\n${monkey}  ${red}Erasing${nc} --> Flash"
    echo "\n--------------------------------------------------------------------------"
    esptool.py --chip esp32 --port ${PORT} --baud ${BAUD} --before default_reset --after hard_reset erase_flash
fi
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erase Storage ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
clear
    echo "\n--------------------------------------------------------------------------"
    echo "\n${monkey}  ${red}Erasing${nc} --> Storage"
    echo "\n--------------------------------------------------------------------------"
    esptool.py --chip esp32 --port ${PORT} --baud ${BAUD} erase_region 0xf00000 0x100000
fi