#!/bin/zsh

#---------------------------------
# import styles
#---------------------------------
source styles

# port
port() {
  clear
  PORTS=(/dev/cu*)
  OPTION="${monkey}  ${red}Please Select a ${cyan}COM Port? ${nc}"
  echo "\n--------------------------------------------------------------------------"
  echo "\n${OPTION}"
  echo "\n--------------------------------------------------------------------------"  
  select PORT in "${PORTS[@]}"
  do
    case $PORT in
      * ) 
        if [[ $PORT[0,1] ]]
        then
          clear
          echo "\n--------------------------------------------------------------------------"
          echo "\n${squid}  ${green}Selected ${cyan}${PORT#*.} ${nc}"
          echo "\n--------------------------------------------------------------------------"
          sleep 0.5
          clear
          break
        else
          port
        fi
    esac
  done  
}

port


