#!/bin/zsh

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export redbg='\e[1;41m'
export greenbg='\e[1;42m'
export yellowbg='\e[1;43m'
export bluebg='\e[1;44m'
export magentabg='\e[1;45m'
export cyanbg='\e[1;46m'
export whitebg='\e[1;47m'                      
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️
