#!/bin/bash

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\033[0m' # No Color
export bold='\033[1m' # No Color
export red='\033[31m'
export green='\033[32m'
export yellow='\033[33m'
export blue='\033[34m'
export magenta='\033[35m'
export cyan='\033[36m'
export white='\033[37m'
export redbg='\033[41m'
export greenbg='\033[42m'
export yellowbg='\033[43m'
export bluebg='\033[44m'
export magentabg='\033[45m'
export cyanbg='\033[46m'
export whitebg='\033[47m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export dog=🐶
export cat=🐱
export cow=🐮
export hamster=🐹
export rabbit=🐰
export dragon=🐲
export fire=🔥
export bomb=💣
export game=🕹️
export pad=🎮
export memo=📝
export wrench=🛠
export disk=💾
export wave=👋
export screen=🖥️
export file=🗄️
export clamp=🗜️
