#!/bin/zsh

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️


#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
ESP="$REPO/Tools/esp-idf"
ODROID="$REPO/Odroid/odroid-go-firmware"
GOPLAY="$REPO/Launchers/go-play"

clear
cd $ESP
required="release/v3.2-odroid"
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${yellow}Checking ${magenta}'esp-idf'${nc} for ${red}${required}${nc} branch"
echo "\n--------------------------------------------------------------------------"
#git checkout -b ${required} origin/${required}
sleep 1
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Success ${magenta}'esp-idf'${nc} is now on ${green}$(git rev-parse --abbrev-ref HEAD)${nc} branch"
echo "\n--------------------------------------------------------------------------"
sleep 1
clear
cd $ODROID
required="esp-idf-v3.2"
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${yellow}Checking ${magenta}'odroid-go-firmware'${nc} for ${red}${required}${nc} branch"
echo "\n--------------------------------------------------------------------------"
#git checkout -b ${required} origin/${required}
sleep 1
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Success ${magenta}'odroid-go-firmware'${nc} is now on ${green}$(git rev-parse --abbrev-ref HEAD)${nc} branch"
echo "\n--------------------------------------------------------------------------"
sleep 1
clear
cd $GOPLAY
required="master"
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${yellow}Checking ${magenta}'go-play'${nc} for ${red}${required}${nc} branch"
echo "\n--------------------------------------------------------------------------"
#git checkout -b ${required} origin/${required}
sleep 1
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Success ${magenta}'go-play'${nc} is now on ${green}$(git rev-parse --abbrev-ref HEAD)${nc} branch"
echo "\n--------------------------------------------------------------------------"
