#!/bin/zsh

export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳

# port
port() {
  clear
  PORTS=(/dev/cu*)
  OPTION="${monkey}  ${red}Please Select a ${cyan}COM Port? ${nc}"
  echo "\n--------------------------------------------------------------------------"
  echo "\n${OPTION}"
  echo "\n--------------------------------------------------------------------------"  
  select PORT in "${PORTS[@]}"
  do
    case $PORT in
      * ) 
        if [[ $PORT[0,1] ]]
        then
          clear
          echo "\n--------------------------------------------------------------------------"
          echo "\n${squid}  ${green}Selected ${cyan}${PORT#*.} ${nc}"
          echo "\n--------------------------------------------------------------------------"
          sleep 1
          break
        else
          port
        fi
    esac
  done  
}

port

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erasing Flash and Storage ${nc}[y/N]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
    clear
    echo "\n--------------------------------------------------------------------------"
    echo "\n${monkey}  ${red}Erasing${nc} --> Flash"
    echo "\n--------------------------------------------------------------------------"
    esptool.py --chip esp32 --port ${PORT} --baud 921600 --before default_reset --after hard_reset erase_flash
fi

echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erasing Storage ${nc}[y/N]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
clear
    echo "\n--------------------------------------------------------------------------"
    echo "\n${monkey}  ${red}Erasing${nc} --> Storage"
    echo "\n--------------------------------------------------------------------------"
    esptool.py --chip esp32 --port ${PORT} --baud 921600 erase_region 0xf00000 0x100000
fi

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}GOODBYE${nc}"
echo "\n--------------------------------------------------------------------------"