#!/bin/zsh

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------
export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"
export IDF_PATH=~/esp/esp-idf

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
GOGO_PATH="$REPO/gogo/"
GOPLAY_PATH="$REPO/go-play/"
FIRMWARE_PATH="$REPO/Firmware"
MKFW_PATH="$REPO/odroid-go-firmware/tools/mkfw"

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️


echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Launcher? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"

read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Compiling ${cyan}Launcher${nc}"
  echo "\n--------------------------------------------------------------------------"  
  echo "Compiling Launcher"
  cd $GOGO_PATH
  make -j8
  cp ./build/gogo.bin $SRC_PATH
fi
clear

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Emulators? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  cd $GOPLAY_PATH

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${lion}  ${green}Compiling ${cyan}gnuboy${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd gnuboy-go
  make -j8
  cp ./build/gnuboy-go.bin $SRC_PATH

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${green}Compiling ${cyan}nesemu${nc}"
  echo "\n--------------------------------------------------------------------------"  
  cd ../nesemu-go
  make -j8
  cp ./build/nesemu-go.bin $SRC_PATH

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${panda}  ${green}Compiling ${cyan}smsplusgx${nc}"
  echo "\n--------------------------------------------------------------------------"    
  cd ../smsplusgx-go
  make -j8
  cp ./build/smsplusgx-go.bin $SRC_PATH
fi

echo "\n--------------------------------------------------------------------------"
echo "\n${panda}  ${green}Creating ${cyan}Gaboze Express${nc} Firmware"
echo "\n--------------------------------------------------------------------------"

cd $SRC_PATH

echo "Building mkfw"
cd $MKFW_PATH
make 

cd $SRC_PATH
ffmpeg -i assets/gaboze.png -f rawvideo -pix_fmt rgb565 assets/gaboze.raw -y

$MKFW_PATH/mkfw 'Gaboze Express' assets/gaboze.raw \
0 16 1048576 gogo gogo.bin \
0 17 1048576 nesemu-go nesemu-go.bin \
0 18 1048576 gnuboy-go gnuboy-go.bin \
0 19 2097152 smsplusgx-go smsplusgx-go.bin

mv firmware.fw $FIRMWARE_PATH/GabozeExpress.fw

clear

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Delete ${cyan}Binaries? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
    clear
    rm gogo.bin
    rm gnuboy-go.bin
    rm nesemu-go.bin
    rm smsplusgx-go.bin  
fi
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Copmleted ${cyan}Gaboze Express${nc}"
echo "\n--------------------------------------------------------------------------"
exit
#---------------------------------
# DON'T TOUCH END
#---------------------------------