#!/bin/zsh

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------

source paths

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
FIRMWARE_PATH="$REPO/Firmware"
GOGO_PATH="$REPO/Launchers/gogo/"
GENERIC_PATH="$REPO/Launchers/emulator-launcher-odroid-go/"
GOPLAY_PATH="$REPO/Launchers/go-play/"
MKFW_PATH="$REPO/Odroid/odroid-go-firmware/tools/mkfw"
LAUNCHER_PATH=""
LAUNCHER=""
BIN=""

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️

OPTION="${monkey}  ${red}Please Select a ${cyan}Launcher? ${nc}"

echo "\n--------------------------------------------------------------------------"
echo "\n${OPTION}"
echo "\n--------------------------------------------------------------------------"
select launcher in "GoGo" "Generic" "Exit"; do
  case $launcher in
    GoGo )
      LAUNCHER="GoGo"
      LAUNCHER_PATH=${GOGO_PATH}
      BIN="gogo"
    break;;
    Generic )
      LAUNCHER="Generic"
      LAUNCHER_PATH=${GENERIC_PATH}
      BIN="emulator-launcher-odroid-go"
    break;;
    Exit ) break;;
    * ) echo "${OPTION}";;
  esac
done

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Launcher? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"

read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Compiling ${cyan}Launcher${nc}"
  echo "\n--------------------------------------------------------------------------"
  echo "Compiling Launcher"
  cd $LAUNCHER_PATH
  make -j8

  if [[ "$LAUNCHER" = "GoGo" ]]
  then
    cp ./build/gogo.bin $FIRMWARE_PATH/Bins/
  fi

  if [[ "$LAUNCHER" = "Generic" ]]
  then
    cp ./build/emulator-launcher-odroid-go.bin $FIRMWARE_PATH/Bins/
  fi
fi
clear

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Emulators? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  cd $GOPLAY_PATH

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${lion}  ${green}Compiling ${cyan}gnuboy${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd gnuboy-go
  make -j8
  cp ./build/gnuboy-go.bin $FIRMWARE_PATH/Bins/

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${green}Compiling ${cyan}nesemu${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ../nesemu-go
  make -j8
  cp ./build/nesemu-go.bin $FIRMWARE_PATH/Bins/

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${panda}  ${green}Compiling ${cyan}smsplusgx${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ../smsplusgx-go
  make -j8
  cp ./build/smsplusgx-go.bin $FIRMWARE_PATH/Bins/
fi

echo "\n--------------------------------------------------------------------------"
echo "\n${panda}  ${green}Creating ${cyan}Gaboze Express${nc} Firmware"
echo "\n--------------------------------------------------------------------------"

cd $SRC_PATH

echo "Building mkfw"
cd $MKFW_PATH
make

cd $SRC_PATH
ffmpeg -i $FIRMWARE_PATH/Assets/gaboze.png -f rawvideo -pix_fmt rgb565 $FIRMWARE_PATH/Assets/gaboze.raw -y

$MKFW_PATH/mkfw 'Gaboze Express' $FIRMWARE_PATH/Assets/gaboze.raw \
0 16 1048576 ${BIN} $FIRMWARE_PATH/Bins/${BIN}.bin \
0 17 1048576 nesemu-go $FIRMWARE_PATH/Bins/nesemu-go.bin \
0 18 1048576 gnuboy-go $FIRMWARE_PATH/Bins/gnuboy-go.bin \
0 19 2097152 smsplusgx-go $FIRMWARE_PATH/Bins/smsplusgx-go.bin

mv firmware.fw $FIRMWARE_PATH/Releases/${BIN}.fw

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Copmleted ${cyan}Gaboze Express${nc}"
echo "\n--------------------------------------------------------------------------"
exit
#---------------------------------
# DON'T TOUCH END
#---------------------------------
