#!/bin/zsh

#---------------------------------
# Styles
#---------------------------------
source helpers/styles

SCRIPTS=$PWD
TAR=''

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}(Re)Install ${cyan}xtensa-esp32? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${green}Downloading ${cyan}xtensa-esp32${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ~/Downloads
  OS="`uname`"
  case $OS in
    'Linux')
      TAR='xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz'
      ;;
    'Darwin')
      TAR='xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz'
      ;;
    *) ;;
  esac
  [ -e ${TAR} ] && \
  rm  ${TAR}

  curl https://dl.espressif.com/dl/${TAR} \
  --output ${TAR} \
  --progress-bar
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${blue}Extracting ${cyan}xtensa-esp32${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ~/esp
  tar -xzf ~/Downloads/${TAR}
  sleep 1
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${blue}Preparing ${cyan}environment variables${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ${SCRIPTS}

  #---------------------------------
  # ESP32
  #---------------------------------
  source helpers/esp32

  #---------------------------------
  # Paths
  #---------------------------------
  source helpers/paths

  #---------------------------------
  # Goodbye
  #---------------------------------
  source helpers/goodbye
fi
clear

#---------------------------------
# Styles
#---------------------------------
source helpers/esp32

#---------------------------------
# Goodbye
#---------------------------------
source helpers/goodbye
sleep 1
clear
