#!/bin/zsh

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️

SCRIPTS=$PWD
TAR=''

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}(Re)Install ${cyan}xtensa-esp32? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then  
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${green}Downloading ${cyan}xtensa-esp32${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ~/Downloads
  OS="`uname`"
  case $OS in
    'Linux')
      TAR='xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz'
      ;;
    'Darwin') 
      TAR='xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz'
      ;;
    *) ;;
  esac  
  [ -e ${TAR} ] && \
  rm  ${TAR}
  
  curl https://dl.espressif.com/dl/${TAR} \
  --output ${TAR} \
  --progress-bar
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${blue}Extracting ${cyan}xtensa-esp32${nc}"
  echo "\n--------------------------------------------------------------------------"  
  cd ~/esp
  tar -xzf ~/Downloads/${TAR}
  sleep 1
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${blue}Preparing ${cyan}environment variables${nc}"
  echo "\n--------------------------------------------------------------------------"    
  cd ${SCRIPTS}
  source paths  
else
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${unicorn}  ${magenta}Goodbye${nc}"
  echo "\n--------------------------------------------------------------------------"    
fi
sleep 1
clear