#!/bin/zsh

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------
source paths

#---------------------------------
# EDIT PORT ESP32
#---------------------------------
export PORT='/dev/cu.usbserial-AE01AFBX'
# export PORT='/dev/cu.SLAB_USBtoUART'

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
FIRMWARE_PATH="$REPO/Firmware"
GOGO_PATH="$REPO/Launchers/gogo/"
GABOZE_PATH="$REPO/Launchers/gaboze/"
GENERIC_PATH="$REPO/Launchers/emulator-launcher-odroid-go/"
GOPLAY_PATH="$REPO/Launchers/go-play/"
LAUNCHER_PATH=""
LAUNCHER=""
BIN=""

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️

OPTION="${monkey}  ${red}Please Select a ${cyan}Launcher? ${nc}"

echo "\n--------------------------------------------------------------------------"
echo "\n${OPTION}"
echo "\n--------------------------------------------------------------------------"
select launcher in "GoGo" "Gaboze" "Generic" "Exit"; do
  case $launcher in
    GoGo )
      LAUNCHER="GoGo"
      LAUNCHER_PATH=${GOGO_PATH}
      BIN="gogo"
    break;;
    Gaboze )
      LAUNCHER="Gaboze"
      LAUNCHER_PATH=${GABOZE_PATH}
      BIN="gaboze"
    break;;    
    Generic )
      LAUNCHER="Generic"
      LAUNCHER_PATH=${GENERIC_PATH}
      BIN="emulator-launcher-odroid-go"
    break;;
    Exit ) break;;
    * ) echo "${OPTION}";;
  esac
done

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Launcher? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Compiling ${cyan}Launcher${nc}"
  echo "\n--------------------------------------------------------------------------"

  rm $FIRMWARE_PATH/Bins/bootloader.bin
  rm $FIRMWARE_PATH/Bins/partitions.bin

  if [[ "$LAUNCHER" = "GoGo" ]]
  then
    rm $FIRMWARE_PATH/Bins/gogo.bin
  fi

  if [[ "$LAUNCHER" = "Gaboze" ]]
  then
    rm $FIRMWARE_PATH/Bins/gaboze.bin
  fi  

  if [[ "$LAUNCHER" = "Generic" ]]
  then
    rm $FIRMWARE_PATH/Bins/emulator-launcher-odroid-go.bin
  fi

  cd $LAUNCHER_PATH
  make -j8
  cp ./build/bootloader/bootloader.bin $FIRMWARE_PATH/Bins/
  cp ./build/partitions.bin $FIRMWARE_PATH/Bins/

  if [[ "$LAUNCHER" = "GoGo" ]]
  then
    cp ./build/gogo.bin $FIRMWARE_PATH/Bins/
  fi

  if [[ "$LAUNCHER" = "Gaboze" ]]
  then
    cp ./build/gaboze.bin $FIRMWARE_PATH/Bins/
  fi  

  if [[ "$LAUNCHER" = "Generic" ]]
  then
    cp ./build/emulator-launcher-odroid-go.bin $FIRMWARE_PATH/Bins/
  fi
fi
clear



echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Emulators? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  rm $FIRMWARE_PATH/Bins/gnuboy-go.bin
  rm $FIRMWARE_PATH/Bins/nesemu-go.bin
  rm $FIRMWARE_PATH/Bins/smsplusgx-go.bin

  cd $GOPLAY_PATH


  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${lion}  ${green}Compiling ${cyan}gnuboy${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd gnuboy-go
  make -j8
  cp ./build/gnuboy-go.bin $FIRMWARE_PATH/Bins/

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${green}Compiling ${cyan}nesemu${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ../nesemu-go
  make -j8
  cp ./build/nesemu-go.bin $FIRMWARE_PATH/Bins/

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${panda}  ${green}Compiling ${cyan}smsplusgx${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd ../smsplusgx-go
  make -j8
  cp ./build/smsplusgx-go.bin $FIRMWARE_PATH/Bins/
fi

cd $SRC_PATH

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erasing Flash and Storage ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${red}Erasing${nc} --> Flash"
  echo "\n--------------------------------------------------------------------------"
  esptool.py --chip esp32 --port ${PORT} --baud 921600 --before default_reset --after hard_reset erase_flash
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${red}Erasing${nc} --> Storage"
  echo "\n--------------------------------------------------------------------------"
  esptool.py --chip esp32 --port ${PORT} --baud 921600 erase_region 0xf00000 0x100000
fi

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${game}  ${green}Flashing Device ${nc} - Hang Tight"
echo "\n--------------------------------------------------------------------------"
esptool.py \
--chip esp32 \
--port ${PORT} \
--baud 921600 \
--before default_reset \
--after hard_reset write_flash -z \
--flash_mode dio \
--flash_freq 40m \
--flash_size detect \
0x1000 $FIRMWARE_PATH/Bins/bootloader.bin \
0x8000 $FIRMWARE_PATH/Bins/partitions.bin \
0x10000 $FIRMWARE_PATH/Bins/${BIN}.bin \
0x200000 $FIRMWARE_PATH/Bins/${BIN}.bin \
0x300000 $FIRMWARE_PATH/Bins/nesemu-go.bin \
0x400000 $FIRMWARE_PATH/Bins/gnuboy-go.bin \
0x500000 $FIRMWARE_PATH/Bins/smsplusgx-go.bin

echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Copmleted ${cyan}Gaboze Express${nc}"
echo "\n--------------------------------------------------------------------------"
exit
#---------------------------------
# DON'T TOUCH END
#---------------------------------
