#!/bin/zsh

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------
export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"
export IDF_PATH=~/esp/esp-idf

#---------------------------------
# EDIT PORT ESP32
#---------------------------------
export PORT='/dev/cu.SLAB_USBtoUART'

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
GOGO_PATH="$REPO/gogo/"
GOPLAY_PATH="$REPO/go-play/"
FIRMWARE_PATH="$REPO/Firmware"
MKFW_PATH="$REPO/odroid-go-firmware/tools/mkfw"

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️


echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Launcher? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"

read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Compiling ${cyan}Launcher${nc}"
  echo "\n--------------------------------------------------------------------------"  
  echo "Compiling Launcher"
  rm $SRC_PATH/bin/bootloader.bin
  rm $SRC_PATH/bin/partitions.bin
  rm $SRC_PATH/bin/partitions_singleapp.bin
  rm $SRC_PATH/bin/gogo.bin

  cd $GOGO_PATH
  make clean
  make -j8
  cp ./build/bootloader/bootloader.bin $SRC_PATH/bin
  cp ./build/partitions.bin $SRC_PATH/bin  
  cp ./build/gogo.bin $SRC_PATH/bin $SRC_PATH/bin
fi
clear

echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Recompile ${cyan}Emulators? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  rm $SRC_PATH/bin/gnuboy-go.bin
  rm $SRC_PATH/bin/nesemu-go.bin
  rm $SRC_PATH/bin/smsplusgx-go.bin   
    
  cd $GOPLAY_PATH


  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${lion}  ${green}Compiling ${cyan}gnuboy${nc}"
  echo "\n--------------------------------------------------------------------------"
  cd gnuboy-go
  make clean  
  make -j8
  cp ./build/gnuboy-go.bin $SRC_PATH/bin

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${fox}  ${green}Compiling ${cyan}nesemu${nc}"
  echo "\n--------------------------------------------------------------------------"  
  cd ../nesemu-go
  make clean  
  make -j8
  cp ./build/nesemu-go.bin $SRC_PATH/bin

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${panda}  ${green}Compiling ${cyan}smsplusgx${nc}"
  echo "\n--------------------------------------------------------------------------"    
  cd ../smsplusgx-go
  make clean  
  make -j8
  cp ./build/smsplusgx-go.bin $SRC_PATH/bin
fi

cd $SRC_PATH

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${red}Erasing Flash and Storage ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"
read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${red}Erasing${nc} --> Flash"
  echo "\n--------------------------------------------------------------------------"
  esptool.py --chip esp32 --port ${PORT} --baud 921600 --before default_reset --after hard_reset erase_flash
  echo "\n--------------------------------------------------------------------------"
  echo "\n${monkey}  ${red}Erasing${nc} --> Storage"
  echo "\n--------------------------------------------------------------------------"  
  esptool.py --chip esp32 --port ${PORT} --baud 921600 erase_region 0xf00000 0x100000
fi

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${game}  ${green}Flashing Device ${nc} - Hang Tight"
echo "\n--------------------------------------------------------------------------"
esptool.py \
--chip esp32 \
--port ${PORT} \
--baud 921600 \
--before default_reset \
--after hard_reset write_flash -z \
--flash_mode dio \
--flash_freq 80m \
--flash_size detect \
0x1000 bin/bootloader.bin \
0x8000 bin/partitions.bin \
0x10000 bin/gogo.bin \
0x200000 bin/gogo.bin \
0x300000 bin/nesemu-go.bin \
0x400000 bin/gnuboy-go.bin \
0x500000 bin/smsplusgx-go.bin

echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Copmleted ${cyan}Gaboze Express${nc}"
echo "\n--------------------------------------------------------------------------"
exit
#---------------------------------
# DON'T TOUCH END
#---------------------------------