#!/bin/zsh

export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳

REPO=$(dirname $PWD)

clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${green}Adding${nc} --> PATH"
echo "\n--------------------------------------------------------------------------"
#export PATH=$HOME/esp/xtensa-esp32-elf/bin:$PATH
export PATH="$HOME/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin":$PATH
sleep 1
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${monkey}  ${green}Adding${nc} --> IDF_PATH"
echo "\n--------------------------------------------------------------------------"
#export IDF_PATH=$REPO/Tools/esp-idf
export IDF_PATH=$HOME/esp/esp-idf
sleep 1
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}GOODBYE${nc}"
echo "\n--------------------------------------------------------------------------"
