#!/bin/bash

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------
export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
COMPONENTS="$REPO/Components"
LAUNCHERS="$REPO/Launchers"
EMULATORS="$REPO/Emulators"
ODROID="$REPO/Odroid"

#---------------------------------
# Styles
#---------------------------------
source helpers/styles


echo "--------------------------------------------------------------------------"
echo -e "${game}  ${white}LCD Screen Driver Option"
echo -e "This will add a ${white}Kconfig.projbuild${nc} for the TFT Display"
echo -e "Running ${magenta}'make menuconfig'${nc}  will provide you option to set:"
echo -e "${cyanbg} ${white}LCD Screen Driver                                          ${nc}"
echo -e "\t${white}1.${nc} Odroid Go Default (ILI9341) [2.4\"] ${bluebg}  default  ${nc}"
echo -e "\t${white}2.${nc} Retro ESP32 (ILI9342) [2.6\"]"
echo -e "${cyanbg} ${white}Retro ESP32 - In Game Menu                                 ${nc}"
echo -e "\t${white}1.${nc} Yes"
echo -e "\t${white}2.${nc} No ${bluebg}  default  ${nc}"
echo -e "${cyanbg} ${white}Menu Hot Keys                                              ${nc}"
echo -e "\t${white}1.${nc} Default Odroid Go MENU Button ${bluebg}  default  ${nc}"
echo -e "\t${white}2.${nc} Use START + SELECT buttons for MENU"
echo -e " ${nc}${green}Add Option?${nc} [y/${bold}N${nc}]"
echo "--------------------------------------------------------------------------"

read -n 1 -r response
if [[ "$response" = "y" ]]
then
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${squid}  ${green}Replacing ${cyan}odroid-go-firmware${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/odroid-go-firmware/main/* $ODROID/odroid-go-firmware/main
  sleep 0.25

  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${robot}  ${green}Replacing ${cyan}go-play${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/go-play/* $EMULATORS/go-play
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${robot}  ${green}Replacing ${cyan}super-go-play${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/super-go-play/* $EMULATORS/super-go-play
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${robot}  ${green}Replacing ${cyan}pitpo${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/pitpo/* $EMULATORS/pitpo
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${fox}  ${green}Replacing ${cyan}handy-go${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/handy-go/* $EMULATORS/handy-go
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${fox}  ${green}Replacing ${cyan}odroid-go-pcengine-huexpress${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/odroid-go-pcengine-huexpress/* $EMULATORS/odroid-go-pcengine-huexpress
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${fox}  ${green}Replacing ${cyan}frodo-go${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/frodo-go/* $EMULATORS/frodo-go
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${lion}  ${green}Replacing ${cyan}prosystem-odroid-go${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/prosystem-odroid-go/* $EMULATORS/prosystem-odroid-go
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${monkey}  ${green}Replacing ${cyan}stella-odroid-go${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/stella-odroid-go/* $EMULATORS/stella-odroid-go
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${panda}  ${green}Replacing ${cyan}emulator-launcher-odroid-go${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/emulator-launcher-odroid-go/* $LAUNCHERS/emulator-launcher-odroid-go
  sleep 0.25
  clear
  echo "--------------------------------------------------------------------------"
  echo -e "${whale}  ${green}Replacing ${cyan}gogo${nc} files"
  echo "--------------------------------------------------------------------------"
  cp -R $COMPONENTS/gogo/* $LAUNCHERS/gogo
  sleep 0.25
fi

#---------------------------------
# Goodbye
#---------------------------------
source helpers/goodbye
