#!/bin/zsh

SRC_PATH=`pwd`

#---------------------------------
# EDIT PATHS FOR ESP AND IDF
#---------------------------------
export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"

#---------------------------------
# DON'T TOUCH START
#---------------------------------
REPO=$(dirname $PWD)
COMPONENTS="$REPO/Components"
LAUNCHERS="$REPO/Launchers"
EMULATORS="$REPO/Emulators"
ODROID="$REPO/Odroid"

#---------------------------------
# FANCY STUFF
#---------------------------------
export nc='\e[0m' # No Color
export red='\e[1;31m'
export green='\e[1;32m'
export yellow='\e[1;33m'
export blue='\e[1;34m'
export magenta='\e[1;35m'
export cyan='\e[1;36m'
export white='\e[1;37m'
export today=`date +%A\ %B\ %d\ %Y\ %T`

export squid=🐙
export robot=🤖
export unicorn=🦄
export fox=🦊
export lion=🦁
export monkey=🐵
export chicken=🐔
export panda=🐼
export whale=🐳
export game=🕹️


echo "\n--------------------------------------------------------------------------"
echo "\n${squid}  ${red}Replace ${cyan}ILI9342 Specific Files? ${nc}[y/${white}N${nc}]"
echo "\n--------------------------------------------------------------------------"

read -rs -k 1 response
if [[ "$response" = "y" ]]
then
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}odroid-go-firmware${nc} files"
  echo "\n--------------------------------------------------------------------------"
  cp -R $COMPONENTS/odroid-go-firmware/main/* $ODROID/odroid-go-firmware/main
  sleep 1

  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}go-play${nc} files"
  echo "\n--------------------------------------------------------------------------"
  cp -R $COMPONENTS/go-play/* $EMULATORS/go-play
  sleep 1  
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}frodo-go${nc} files"
  echo "\n--------------------------------------------------------------------------"  
  cp -R $COMPONENTS/frodo-go/* $EMULATORS/frodo-go
  sleep 1
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}prosystem-odroid-go${nc} files"
  echo "\n--------------------------------------------------------------------------"  
  cp -R $COMPONENTS/prosystem-odroid-go/* $EMULATORS/prosystem-odroid-go
  sleep 1
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}stella-odroid-go${nc} files"
  echo "\n--------------------------------------------------------------------------"  
  cp -R $COMPONENTS/stella-odroid-go/* $EMULATORS/stella-odroid-go
  sleep 1
  clear
  echo "\n--------------------------------------------------------------------------"
  echo "\n${squid}  ${green}Replacing ${cyan}emulator-launcher-odroid-go${nc} files"
  echo "\n--------------------------------------------------------------------------"
  cp -R $COMPONENTS/emulator-launcher-odroid-go/* $LAUNCHERS/emulator-launcher-odroid-go
  sleep 1
fi
clear
echo "\n--------------------------------------------------------------------------"
echo "\n${unicorn}  ${green}Goodbye${nc}"
echo "\n--------------------------------------------------------------------------"
exit
